apiVersion: v1
kind: Secret
metadata:
    name: secret-mysql
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:9VG7dBNwpvU1PqxIUQXRvJseItsEsR9mTw==,iv:If2QBplVpo1iszCW0GLFohM5k9zUzhWB9rPJFqnLFj0=,tag:gpAcidUg7i+68txmwV2y7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-20T12:50:28Z"
    mac: ENC[AES256_GCM,data:t9D/5N7NVPNZj2Ee9YXIpRU5Mq0is41foaQndp/5h7fkeZMnUXSjIGDLHorcoUbsjCZcAt4PIE5c+VDe5muoQ4wUbIJPCu/Dcq8OWjl7fgc4dPef4dJ3a6Siq1EW5QNzoLQicx2WQj2jMSjxgm4VEOXVLshqiWjDwxArnoHkpHw=,iv:Zj++sy419xT3tWBTj3AU6lIImGJPJyRrElkhx/n4tbs=,tag:4kIR5oJ6FSKrhFDHPAt8rQ==,type:str]
    pgp:
        - created_at: "2025-11-20T12:50:27Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA6QWYhLlmtsSAQv/WAi8b6eTz7tN3Amym7btHcEDT63o5ZJzdwLk5h8ETsG7
            9ntyGFcQVyI/4EF2S9oG0C0lamgwMgK+VVoGP3ueWYvTY0AcMbmuvqxRVZLqS0Jn
            hqZ9+v5p/cmitzCBYed+rnlpM573Gf/e7tnqAFEvWnERbU+sOr1fp3+pPY9NEiwi
            B/2akU9WbzKNpe11jqC1ZSS+gKPiVm4i/plaBI66BHIJrE25C1FcYeaKzgu7hP9Y
            DeLfPr79FwppJ6L/LG0gIkf9g3ngaciB/n8Ee1ii2qUgTmJxAoEltQ1w19vjUEjp
            IwHtxMkBPzjF8Pdgz07RPqGHqfIjLnQZl9rEulA/w1g3zxpODN6xDSrEP7ljWKAa
            cyIf/RxdBcqdoTQsNUlowjiBU/i8mnf5Cga7H0MFmZYC0qLABRJwNP03pHR+bU0A
            rsSSixYfxP5FniO/XX1szGJHFpKn5FyK/1Y+DNJSYQ/4B1oEU5A90wBvLFrnDJql
            /Z6bWYXaX+UICmgBNIDL1GYBCQIQ2hrtj98/e03ERGYovkGWCxLMsoo6iT5BH1rB
            /Xx+nFlIFsRpgSnEiYymh+r519FAzJwKI8iNd82HLCyA+8EJTn5Ff7hxmN8qcheb
            QWmpKiZh5vtok8kFy6k+F3Kpijeg/hI=
            =1RTO
            -----END PGP MESSAGE-----
          fp: 3FA2394B23371F858BBFE5E1E60FEA532B83178D
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
