apiVersion: v1
kind: Secret
metadata:
    name: secret-mysql
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:7+UWxIUWu3JBf9xV6qLgemHF/AGXW4uzHA==,iv:aQU+kTRzGp6GytjFP508GtYiQ1/+Pi9A0dfqZ2S5gzI=,tag:S6TcwP2QcuMnF8uyn+o+7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-29T15:31:37Z"
    mac: ENC[AES256_GCM,data:HSntPZkV2bcDfMP2x20u0J5PH1SptQ5U0kFiQx84hI9sRlr2dhwpCzDy6zDeVtzyysCJhE8xI3obJritbUeumEhbY/hp7+z6/S35u3SjWBwXsyIJKzmObue2/TF8IyxYgNpt9plCUD2RA8zN/K0MCKEdbhrMF0NcYpVMo6ML+6w=,iv:pua1U3HEG05sO5ABSoHGzxI4JsqOR3GD2neP4R780KE=,tag:DeN+KRE+smGzDnWpuD99OQ==,type:str]
    pgp:
        - created_at: "2025-12-29T15:31:37Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA8FL4Hji3HgFAQv+NdjyMCBiWLR9zztc7JvrlygG51LvrpH8Gps3AUmA5xmb
            mLjUretpaGM8HBzzQmuAs6NfCRFG+QpJmE+rgxgGzcHXq0K4xtBnLWtPQAZuGPll
            1m7abtB63nD09lAaYfDzA01RfNBw8rA7vXM5G3E7R9pXrdh/mvhafNO4z7YgcPeY
            2KHIyclXWTtGn0s1w5Odd3Uo2g6XzQrS7jAtAtvO9MLBtH4DG4YqqEU8TY39aUFh
            515vdL0+way98FGkExyy+JzIkuupvwclYbXCMmBdJW34Cd1PJa0gBa/9tOR6N2JJ
            q8IqrvwrzRzpVmEvjbbVGwr4o9m2ged+OTldixMtdkjBEyf2Va7FFHB9j3/pDZCz
            VgoIKhQmk0x0L9BCXmjCkoFbFr0gKLGmIOgPieHRz/Hpi6z5FTqkB42+3h0bNapA
            FNCHcdXy/ZJbgUep94VwTTGAL/gN+jyYhUZajb/lbdqT2SiF4YYzvGXl4V2xAxkM
            q7I3qpaqYaEARfSc8pqf1GYBCQIQuLmVcnaEvgFfHlgBgQkVqoqjT2S8272DqX4r
            fumO0Y5xn94dUMm6GrnNtSc7Smn65sQb6/5nrUG6KmRCFo1/NoAN/H/hWd4DCUDr
            8rc58OPpDKcJjARNTkG3jZ5gzVsGeAc=
            =Jshb
            -----END PGP MESSAGE-----
          fp: 75DA0355FE61BCACAE6E0C43A50B751CAE8F9960
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
